[package]
name = "stabilizing"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = "0.16.0"
la-arena = "0.3.1"
paste = "1.0.15"
rowan = "0.16.1"
rustc-hash = "2.1.1"
syntax = { version = "0.1.0", path = "../syntax" }
