[package]
name = "building-types"
version = "0.1.0"
edition = "2024"

[dependencies]
files = { version = "0.1.0", path = "../files" }
rustc-hash = "2.1.1"
string-interner = "0.19.0"
thiserror = "2.0.16"
