[package]
name = "prim"
version = "0.1.0"
edition = "2024"

[dependencies]
building = { version = "0.1.0", path = "../building" }
files = { version = "0.1.0", path = "../files" }
tempfile = "3.20.0"
url = "2.5.4"
