[package]
name = "lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.1.0"
env_logger = "0.11.5"
tower-lsp = "0.20.0"
indexing = { path = "../indexing" }
lexing = { path = "../lexing" }
parsing = { path = "../parsing" }
log = "0.4.14"
syntax = { path = "../syntax" }
ropey = "1.6.1"
tokio = { version = "1.42.0", features = ["full", "io-std"] }
rowan = "0.16.1"

[dev-dependencies]
test_each_file = "0.3.4"
